### ISSUE TITLE
初始化失败并且打开文件失败

### ISSUE THREAD

**Issue by 15711452567** [gstory0404/file_preview#35]
### 描述
初始化失败，并且提示打开文件失败 1002 文件格式暂不支持
### 设备版本
> 本地flutter版本、设备型号版本

### 插件版本

最新版

### 日志
> 详细的log日志或者截图录屏
```
Unsupported class loader
W OpenDexFilesFromOat: open oat file failed and fallback to load dex file from apk, class_loader = 0x790ae16e84 context = 0x0 dex_location = /data/user/0/com.j/app_tbs/home/default/components/file/6000021/file_dex.jar
W/(25499): Unsupported class loader
I/PackageParsing(25499): com.tencent.tbs.ug.component: compat added android.permission.WRITE_EXTERNAL_STORAGE android.permission.READ_PHONE_STATE
W/TBSOne  (25499): Failed to install or load component file, error: [405] Failed to load entry class com.tencent.tbs.ug.component.TbsReaderEntry in file_dex.jar
W/TBSOne  (25499): java.lang.ClassNotFoundException: com.tencent.tbs.ug.component.TbsReaderEntry
W/TBSOne  (25499): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
W/TBSOne  (25499): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:0)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/TBSOne  (25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/TBSOne  (25499): 	at f.g.a.b.j.c.c.q(Unknown Source:424)
W/TBSOne  (25499): 	at f.g.a.b.j.c.c$e.run(Unknown Source:145)
W/TBSOne  (25499): 	at android.os.Handler.handleCallback(Handler.java:966)
W/TBSOne  (25499): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/TBSOne  (25499): 	at android.os.Looper.loopOnce(Looper.java:205)
W/TBSOne  (25499): 	at android.os.Looper.loop(Looper.java:293)
W/TBSOne  (25499): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/TBSOne  (25499): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tbs/reader/ITbsReaderEntry;
W/TBSOne  (25499): 	at dalvik.system.DexFile.defineClassNative(Native Method)
W/TBSOne  (25499): 	at dalvik.system.DexFile.defineClass(DexFile.java:298)
W/TBSOne  (25499): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
W/TBSOne  (25499): 	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
W/TBSOne  (25499): 	at dalvik.system.DexPathList.findClass(DexPathList.java:532)
W/TBSOne  (25499): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:216)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:6)
W/TBSOne  (25499): 	... 9 more
W/TBSOne  (25499): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tbs.reader.ITbsReaderEntry" on path: DexPathList[[zip file "/data/app/~~zjBG_M6E2buaMVKNaUk8yA=包名-1xLCzr86-uCgAz_aOoqDMg==/base.apk"],nativeLibraryDirectories=[/data/app/~~zjBG_M6E2buaMVKNaUk8yA==/-1xLCzr86-uCgAz_aOoqDMg==/lib/arm64, /data/app/~~zjBG_M6E2buaMVKNaUk8yA==/com.j-1xLCzr86-uCgAz_aOoqDMg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/lib64/module/multimedia, /system/product/lib64]]
W/TBSOne  (25499): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
W/TBSOne  (25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/TBSOne  (25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:20)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/TBSOne  (25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:20)
W/TBSOne  (25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/TBSOne  (25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/TBSOne  (25499): 	... 16 more
W/System.err(25499): [405] Failed to load entry class com.tencent.tbs.ug.component.TbsReaderEntry in file_dex.jar
W/System.err(25499): java.lang.ClassNotFoundException: com.tencent.tbs.ug.component.TbsReaderEntry
W/System.err(25499): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
W/System.err(25499): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:0)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/System.err(25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(25499): 	at f.g.a.b.j.c.c.q(Unknown Source:424)
W/System.err(25499): 	at f.g.a.b.j.c.c$e.run(Unknown Source:145)
W/System.err(25499): 	at android.os.Handler.handleCallback(Handler.java:966)
W/System.err(25499): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err(25499): 	at android.os.Looper.loopOnce(Looper.java:205)
W/System.err(25499): 	at android.os.Looper.loop(Looper.java:293)
W/System.err(25499): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err(25499): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tbs/reader/ITbsReaderEntry;
W/System.err(25499): 	at dalvik.system.DexFile.defineClassNative(Native Method)
W/System.err(25499): 	at dalvik.system.DexFile.defineClass(DexFile.java:298)
W/System.err(25499): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:291)
W/System.err(25499): 	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:772)
W/System.err(25499): 	at dalvik.system.DexPathList.findClass(DexPathList.java:532)
W/System.err(25499): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:216)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:6)
W/System.err(25499): 	... 9 more
W/System.err(25499): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tbs.reader.ITbsReaderEntry" on path: DexPathList[[zip file "/data/app/~~zjBG_M6E2buaMVKNaUk8yA==/com.j-1xLCzr86-uCgAz_aOoqDMg==/base.apk"],nativeLibraryDirectories=[/data/app/~~zjBG_M6E2buaMVKNaUk8yA==/com.j-1xLCzr86-uCgAz_aOoqDMg==/lib/arm64, /data/app/~~zjBG_M6E2buaMVKNaUk8yA==/com.j-1xLCzr86-uCgAz_aOoqDMg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/lib64/module/multimedia, /system/product/lib64]]
W/System.err(25499): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
W/System.err(25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:20)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/System.err(25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.a(Unknown Source:20)
W/System.err(25499): 	at f.g.a.b.j.c.a.e.loadClass(Unknown Source:28)
W/System.err(25499): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(25499): 	... 16 more
W/System.err(25499): 	at f.g.a.b.j.f.i(Unknown Source:82)
W/System.err(25499): 	at f.g.a.c.e.n(Unknown Source:79)
W/System.err(25499): 	at f.g.a.c.d.f(Unknown Source:4)
W/System.err(25499): 	at f.e.a.f.onMethodCall(:66)
W/System.err(25499): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:262)
W/System.err(25499): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(:178)
W/System.err(25499): 	at io.flutter.embedding.engine.dart.DartMessenger.a(:206)
W/System.err(25499): 	at io.flutter.embedding.engine.dart.DartMessenger.b(Unknown Source:0)
W/System.err(25499): 	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
W/System.err(25499): 	at android.os.Handler.handleCallback(Handler.java:966)
W/System.err(25499): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err(25499): 	at android.os.Looper.loopOnce(Looper.java:205)
W/System.err(25499): 	at android.os.Looper.loop(Looper.java:293)
W/System.err(25499): 	at android.app.ActivityThread.main(ActivityThread.java:9685)
W/System.err(25499): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25499): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
W/System.err(25499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)
I/DecorView(25499): navBarColor: fffcfcfc statusBarColor: 0 statusInsets: null navInsets: null
I/DecorView(25499): updateColorViewInt type:1 size: 0 showView:false color:fffcfcfc
I/DecorView(25499): updateColorViewInt type:0 size: 72 showView:false color:0

```

**Comment by gstory0404** [comment]
初始化是否传入了license。
文件格式根据url后缀或者head中Content-Type来判断，查看是否符合支持的文件格式

**Comment by 15711452567** [comment]
初始化传了license

**Comment by 15711452567** [comment]
![image](https://github.com/gstory0404/file_preview/assets/44631699/653deeae-4555-477a-81a7-8c77baa7112e)

**Comment by 15711452567** [comment]
![image](https://github.com/gstory0404/file_preview/assets/44631699/03c60c89-bf60-415f-ba85-6c8f209686fd)

**Comment by gstory0404** [comment]
文档提供的几个测试文件尝试是否可以打开？
设备是否是模拟器？尝试用真机测试 @15711452567

**Comment by 15711452567** [comment]
华为手机1加手机都试了都不行

**Comment by 15711452567** [comment]
![image](https://github.com/gstory0404/file_preview/assets/44631699/65a41af1-7d27-49e8-b003-e69ea9d29593)
@gstory0404

**Comment by 15711452567** [comment]
![image](https://github.com/gstory0404/file_preview/assets/44631699/ac5bcadb-1bd3-4fde-9ebe-1410543a8da1)
@gstory0404

**Comment by gstory0404** [comment]
> ![image](https://github.com/gstory0404/file_preview/assets/44631699/ac5bcadb-1bd3-4fde-9ebe-1410543a8da1)
> @gstory0404 

文件放在vercel上 可能需要科学上网

**Comment by 15711452567** [comment]
这个是需要上VPN吗 
文件放在vercel上面，这个要怎么操作，或者怎么搜索

**Comment by gstory0404** [comment]
手机科学上网 然后加载文件

**Comment by 15711452567** [comment]
好的

**Comment by gstory0404** [comment]
我这边测试初始化没问题 确保自己的licence信息没有问题，我去找个华为手机测试一下

**Comment by 15711452567** [comment]
![image](https://github.com/gstory0404/file_preview/assets/44631699/a982dcfe-513d-41a7-bdda-4d810da66bed)
![image](https://github.com/gstory0404/file_preview/assets/44631699/d0135b8f-7e63-42a1-8d09-45b81d6f94a5)

**Comment by 15711452567** [comment]
大佬，你用华为手机试验有结果吗

**Comment by 15711452567** [comment]
我能看到这个插件的日志吗，他initEngine的时候返回-1，我问腾讯技术人员
![image](https://github.com/gstory0404/file_preview/assets/44631699/fb788fbf-228b-4a26-875a-507610677cd0)

**Comment by 15711452567** [comment]
@gstory0404 这个怎么才能看到日志

**Comment by gstory0404** [comment]
logcat日志里面就有

**Comment by 15711452567** [comment]
@gstory0404 大佬，你有用其他手机测试吗

**Comment by gstory0404** [comment]
> @gstory0404 大佬，你有用其他手机测试吗

自己的小米、三星、华为Y9均正常使用 @15711452567

**Comment by 15711452567** [comment]
我这边可以了，谢谢
